<?php

return [
    'ticket_master' => [
        'keys' => [
            'EZMjWPEfiB5w3iTTspvpEVZu7jkhN7fP', // sung-whi's key
            'vy2R4hEqq991irZAPCNkGn2C9VAAt4Ni', // mike's primary key
            // other keys from Mike
            'UVC8xDzYL9HGPOlNyTBSWx7p87OflmnR',
            'O90ACi4TXXYoq2ZMjq9csRQi1DTjkvf9'
        ],
        'country_codes' => [
            'us',
            'ca',
        ],
        'page_size' => 200,
        'classification_filters' => [
            '-sports',
            '-Food and Drink',
            '-Film',
        ],
    ],
    'event_exclusions' => [
        'fast lane',
        'express lane',
        'club and parking upgrade',
        'vs.',
        'v.',
        'Lexus Lounge',
        'Preshow Experience',
        'Harlem Globetrotters',
        'Magic Pass',
        'Skip the Line',
        'Rock The Lounge',
        'Pre Show Dinner',
        'VIP Upgrade',
        'Vibe Room',
        'Retro Film Series',
        'Premium Box Seat',
        'Shore Club Cabanas',
        'Fastlane',
        'Lawn Chair Rental',
        'Club Upgrade',
        'VIP Club Access',
        'Starplex Pavilion Tailgate Club',
        'Tailgate Experience',
        'Preshow Reception',
        'Hollywood Casino Shuttle',
        'Park & Ride',
        'Market Shed Buffet',
        'Preferred Lawn Upgrade',
        'VIP Club Access',
        'VIP Lounge',
        'VIP Lounge',
        'The Green Room',
        'Lonestar Cabana',
        'River Garden Deck',
        'Pre-show Dinner',
        'River Garden Deck',
        'Early Entry',
        'Pre Concert Dinner',
        'Carrier Comfort Zone',
        'Fast Lane Access',
        'Lawn Chair Rental',
        'Reserved Lawn',
        'Hilltop Cabanas',
        'Flight Deck:',
        'TIFF Bell Lightbox',
        'Fast Lane',
        'Tribute',
        'Mini Club Access',
        'Preferred Viewing Area',
        'Meet & Greet',
        'Meet and Greet',
        'Lawn Chair',
        'Meal Voucher',
        'Party Deck',
        'Premium Box',
        'Box Seats',
        'Live Nation Blanket',
        'NOT A CONCERT TICKET',
    ]
];
